export const USER_REQUESTED_LOGIN_ACTION = 'loginRequested'
export const LOGIN_IN_PROGRESS_ACTION = 'loginInProgress'
export const USER_LOGGED_IN_ACTION = 'logged'
export const LOGIN_FAILED_ACTION = 'loginFailed'
export const DISMISS_LOGIN_ERROR_DIALOG_ACTION = 'dismissLoginErrorDoalog'

export const BILLS_FETCH_REQUESTED_ACTION = 'billsFetchRequested'
export const BILLS_FETCHING_IN_PROGRESS_ACTION = 'biilsFetchingInProgress'
export const BILLS_FETCHED_ACTION = 'billsFetched'
export const BILLS_FETCHING_FAILED = 'billsFetchingFailed'
export const DISMISS_DATA_ERROR_DIALOG_ACTION = 'dismissDataErrorDialog'

export const UPDATE_BILL_ACTION = 'updateBill'
export const UPDATE_BILL_IN_PROGRESS_ACTION = 'updateBillInProgress'
export const BILL_UPDATED_ACTION = 'billUpdated'
export const UPDATE_BILL_FAILED_ACTION = 'updateBillFailed'
export const DISMISS_BILL_UPDATED_DIALOG = 'dismissBillUpdatedDialog'
export const DISMISS_UPDATE_BILL_STATUS_ERROR_DIALOG_ACTION = 'dismissUpdateBillStatusErrorDialog'

export const ORDERS_FETCH_REQUESTED_ACTION = 'ordersFetchRequested'
export const ORDERS_FETCHING_IN_PROGRESS_ACTION = 'biilsFetchingInProgress'
export const ORDERS_FETCHED_ACTION = 'ordersFetched'
export const ORDERS_FETCHING_FAILED = 'ordersFetchingFailed'

export const UPDATE_ORDER_ACTION = 'updateOrder'
export const UPDATE_ORDER_IN_PROGRESS_ACTION = 'updateOrderInProgress'
export const ORDER_UPDATED_ACTION = 'orderUpdated'
export const UPDATE_ORDER_FAILED_ACTION = 'updateOrderFailed'
export const DISMISS_ORDER_UPDATED_DIALOG = 'dismissOrderUpdatedDialog'
export const DISMISS_UPDATE_ORDER_STATUS_ERROR_DIALOG_ACTION = 'dismissUpdateOrderStatusErrorDialog'
